AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Exclude:
    - 'lib/umami/models/*.rb'
    - 'lib/umami/models.rb'
    - 'test/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
