name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          
      - name: Install dependencies
        run: bundle install
        
      - name: Run tests
        run: bundle exec rake
        
      - name: Build gem
        run: gem build umami-read-models.gemspec
        
      - name: Set up RubyGems credentials
        run: |
          mkdir -p ~/.gem
          echo -e "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          
      - name: Publish to RubyGems
        run: |
          gem push *.gem
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.gem'
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}